# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/vga_interface/vga_interface.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface || ORIG_REF_NAME==vga_interface} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_clk_wiz_0_0/vga_interface_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_clk_wiz_0_0 || ORIG_REF_NAME==vga_interface_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_v_axi4s_vid_out_0_0/vga_interface_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==vga_interface_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_v_tc_0_0/vga_interface_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_v_tc_0_0 || ORIG_REF_NAME==vga_interface_v_tc_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_rst_clk_wiz_0_148M_0/vga_interface_rst_clk_wiz_0_148M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_rst_clk_wiz_0_148M_0 || ORIG_REF_NAME==vga_interface_rst_clk_wiz_0_148M_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_xlconstant_0_0/vga_interface_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_xlconstant_0_0 || ORIG_REF_NAME==vga_interface_xlconstant_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_xlslice_0_0/vga_interface_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_xlslice_0_0 || ORIG_REF_NAME==vga_interface_xlslice_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_xlslice_1_0/vga_interface_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_xlslice_1_0 || ORIG_REF_NAME==vga_interface_xlslice_1_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_xlslice_2_0/vga_interface_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_xlslice_2_0 || ORIG_REF_NAME==vga_interface_xlslice_2_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_mymux_0_0/vga_interface_mymux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_mymux_0_0 || ORIG_REF_NAME==vga_interface_mymux_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_processing_system7_0_0/vga_interface_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_processing_system7_0_0 || ORIG_REF_NAME==vga_interface_processing_system7_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_axi_vdma_0_0/vga_interface_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_axi_vdma_0_0 || ORIG_REF_NAME==vga_interface_axi_vdma_0_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_ps7_0_axi_periph_0/vga_interface_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_ps7_0_axi_periph_0 || ORIG_REF_NAME==vga_interface_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_axi_smc_0/vga_interface_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_axi_smc_0 || ORIG_REF_NAME==vga_interface_axi_smc_0} -quiet] -quiet

# IP: bd/vga_interface/ip/vga_interface_auto_pc_0/vga_interface_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_interface_auto_pc_0 || ORIG_REF_NAME==vga_interface_auto_pc_0} -quiet] -quiet

# XDC: bd/vga_interface/vga_interface_ooc.xdc
