set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {reset}]
set_property PACKAGE_PIN N15 [get_ports clk]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
