#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Dec 07 08:20:03 EST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1b590d4639e8495390b585edaf8e7742 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot counter_8b_DFF_testbench_behav xil_defaultlib.counter_8b_DFF_testbench xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1b590d4639e8495390b585edaf8e7742 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot counter_8b_DFF_testbench_behav xil_defaultlib.counter_8b_DFF_testbench xil_defaultlib.glbl -log elaborate.log

