webtalk_init -webtalk_dir /afs/ee.cooper.edu/user/a/ahmad.malik/Lab4/4bit_reg_asynch/4bit_reg_asynch.sim/sim_1/behav/xsim/xsim.dir/fourBitRegAsync_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  6 07:06:46 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e0ea730b-0343-48aa-8e62-cff2b0a85316" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3d3114b0508643ef871648492addd269" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4258.104 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 214964958 -regid "" -xml /afs/ee.cooper.edu/user/a/ahmad.malik/Lab4/4bit_reg_asynch/4bit_reg_asynch.sim/sim_1/behav/xsim/xsim.dir/fourBitRegAsync_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /afs/ee.cooper.edu/user/a/ahmad.malik/Lab4/4bit_reg_asynch/4bit_reg_asynch.sim/sim_1/behav/xsim/xsim.dir/fourBitRegAsync_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /afs/ee.cooper.edu/user/a/ahmad.malik/Lab4/4bit_reg_asynch/4bit_reg_asynch.sim/sim_1/behav/xsim/xsim.dir/fourBitRegAsync_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
