# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/vga_interface_axi_smc_0.xci
# IP: The module: 'vga_interface_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/bd_ce01.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_0/bd_ce01_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_1/bd_ce01_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_2/bd_ce01_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_3/bd_ce01_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_4/bd_ce01_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_5/bd_ce01_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_6/bd_ce01_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_7/bd_ce01_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_8/bd_ce01_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_9/bd_ce01_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_1/bd_ce01_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_1/bd_ce01_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_5/bd_ce01_s00a2s_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_6/bd_ce01_sarn_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_7/bd_ce01_srn_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_8/bd_ce01_m00s2a_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_interface_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/vga_interface_axi_smc_0.xci
# IP: The module: 'vga_interface_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/bd_ce01.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_0/bd_ce01_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_1/bd_ce01_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_2/bd_ce01_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_3/bd_ce01_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_4/bd_ce01_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_5/bd_ce01_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_6/bd_ce01_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_7/bd_ce01_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_8/bd_ce01_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_9/bd_ce01_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_1/bd_ce01_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_1/bd_ce01_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_5/bd_ce01_s00a2s_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_6/bd_ce01_sarn_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_7/bd_ce01_srn_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/bd_0/ip/ip_8/bd_ce01_m00s2a_0_ooc.xdc

# XDC: /afs/ee.cooper.edu/user/a/ahmad.malik/Documents/vga_interface/vga_interface.srcs/sources_1/bd/vga_interface/ip/vga_interface_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_interface_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
